#!/usr/bin/env python3
"""Document a theme's install options with screenshots: `fxcss tweaks`.

Theme READMEs describe their optional stylesheets in prose -- accordions of
flags, "run install.sh -c -n -s" incantations -- and a user assembles their
preferred setup in their head. This renders the answer instead: the base theme,
then every optional stylesheet (and any combination worth blessing), each with
a before/after crop of the region it actually changes.

Output is a folder of PNGs plus TWEAKS.md, written to be committed: relative
image links, and a <details> accordion per tweak so a long option list stays
scannable on GitHub.

A tweak that changes nothing is reported as exactly that. The same silent-noop
problem audit catches for selectors applies to optional sheets, which rot at
least as fast.
"""

import io
import time
from pathlib import Path

from PIL import Image, ImageDraw

from . import core
from .compare import diff_stats

FULL_WIDTH = 1280       # committed full-window shots, repo-friendly
CROP_PAD = 30           # logical px of context around a diff region
MIN_CROP = 120          # a sliver of a crop is unreadable; grow to at least this


def _capture(session, outdir: Path, name: str):
    core._shot(session.m, outdir, name)
    return Image.open(outdir / f"{name}.png").convert("RGB")


def _shrink(image, width):
    if image.width <= width:
        return image
    return image.resize((width, round(image.height * width / image.width)),
                        Image.LANCZOS)


def _crop_box(bbox, size, pad, minimum):
    left, top, right, bottom = bbox
    if right - left < minimum:
        centre = (left + right) // 2
        left, right = centre - minimum // 2, centre + minimum // 2
    if bottom - top < minimum:
        centre = (top + bottom) // 2
        top, bottom = centre - minimum // 2, centre + minimum // 2
    return (max(0, left - pad), max(0, top - pad),
            min(size[0], right + pad), min(size[1], bottom + pad))


def _before_after(base, after, bbox, out_path: Path):
    """A labelled side-by-side crop of just the region that changed."""
    box = _crop_box(bbox, base.size, CROP_PAD * 2, MIN_CROP * 2)
    left = base.crop(box)
    right = after.crop(box)
    left = _shrink(left, 620)
    right = _shrink(right, 620)

    label_h = 26
    gutter = 12
    canvas = Image.new("RGB", (left.width + right.width + gutter,
                               left.height + label_h), (246, 246, 248))
    draw = ImageDraw.Draw(canvas)
    draw.text((6, 6), "before", fill=(90, 90, 96))
    draw.text((left.width + gutter + 6, 6), "after", fill=(20, 110, 60))
    canvas.paste(left, (0, label_h))
    canvas.paste(right, (left.width + gutter, label_h))
    canvas.save(out_path, optimize=True)


def build(session, theme: Path, outdir: Path, variants, flags):
    """Capture base + each tweak, measure each against base, emit TWEAKS.md."""
    outdir.mkdir(parents=True, exist_ok=True)
    session.setup_window()
    time.sleep(2.0)

    base = _capture(session, outdir, "base")
    (outdir / "base.png").unlink()
    _shrink(base, FULL_WIDTH).save(outdir / "base.png", optimize=True)

    entries = []
    for slug, sheets in sorted(variants.items()):
        for sheet in sheets:
            session.m.script(core.LOAD_VARIANT_SHEET, [sheet.resolve().as_uri()])
        time.sleep(1.5)
        after = _capture(session, outdir, slug)
        session.m.script(core.UNLOAD_VARIANT_SHEETS)
        time.sleep(0.8)

        changed, total, mask = diff_stats(base, after)
        pct = 100.0 * changed / total if total else 0.0
        entry = {"slug": slug, "sheets": sheets, "percent": pct, "image": None}
        if changed:
            _before_after(base, after, mask.getbbox(), outdir / f"{slug}-diff.png")
            entry["image"] = f"{slug}-diff.png"
            _shrink(after, FULL_WIDTH).save(outdir / f"{slug}.png", optimize=True)
        else:
            (outdir / f"{slug}.png").unlink()
        entries.append(entry)
        state = f"{pct:.2f}% of the chrome" if changed else "nothing on this Firefox"
        print(f"  {slug}: changes {state}", flush=True)

    info = session.info()
    markdown = render_markdown(theme, entries, flags, info["version"])
    (outdir / "TWEAKS.md").write_text(markdown, encoding="utf-8")
    return entries


def render_markdown(theme: Path, entries, flags, firefox_version):
    """The committable document. Pure, so it is unit-testable."""
    lines = [
        "# Tweaks and install options",
        "",
        f"Every optional stylesheet this theme ships, rendered against Firefox "
        f"{firefox_version} and compared with the base setup. Generated by "
        f"[fxcss](https://github.com/AdamXweb/fxcss) — regenerate with "
        f"`fxcss tweaks` after adding an option.",
        "",
        "## Base",
        "",
        "![the theme with no options enabled](base.png)",
        "",
        "## Options",
        "",
    ]

    for entry in entries:
        slug = entry["slug"]
        title = slug.replace("+", " + ")
        if entry["image"]:
            summary = f"<b>{title}</b> — changes {entry['percent']:.2f}% of the chrome"
        else:
            summary = (f"<b>{title}</b> — changes nothing on current Firefox, "
                       f"possibly stale")
        lines.append("<details>")
        lines.append(f"<summary>{summary}</summary>")
        lines.append("")
        if entry["image"]:
            lines.append(f"![before and after of {title}]({entry['image']})")
            lines.append("")
            lines.append(f"Full window: [{slug}.png]({slug}.png)")
            lines.append("")
        enable = ", ".join(f"`{sheet_path_for_doc(theme, s)}`" for s in entry["sheets"])
        lines.append(f"Enable by copying {enable} into your profile's `chrome/` "
                     f"folder (or with the installer flags below, if the theme "
                     f"documents one for it).")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    if flags:
        lines += [
            "## Install script options",
            "",
            "As documented by the theme's own README:",
            "",
            "| flag | effect |",
            "| --- | --- |",
        ]
        lines += [f"| `{f['flag']}` | {f['text']} |" for f in flags]
        lines.append("")
    return "\n".join(lines)


def sheet_path_for_doc(theme: Path, sheet: Path):
    try:
        return str(sheet.relative_to(theme))
    except ValueError:
        return sheet.name


def readme_flags(theme: Path):
    """The theme README's documented install flags, if any."""
    from .fetch import FLAG_LINE
    for name in ("README.md", "readme.md", "README", "README.rst"):
        path = theme / name
        if not path.is_file():
            continue
        found = []
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            match = FLAG_LINE.match(line)
            if match:
                found.append({"flag": match.group(1), "text": match.group(2)})
        return found[:20]
    return []
